<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
      <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="appsettings.Local.example.json" />
    <Content Remove="appsettings.Local.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.Local.json" />
    <None Include="appsettings.Local.example.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Heron.MudCalendar" Version="3.3.0" />
    <PackageReference Include="MudBlazor" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\2025\PuzzleDays\PuzzleDays.csproj" />
    <ProjectReference Include="..\..\Libraries\Helpers\Helpers.csproj" />
  </ItemGroup>

</Project>
